### ISSUE TITLE
Support for Typescript

### ISSUE THREAD

**Issue by anonimitoraf** [jamesdiacono/Replete#3]
`const x: string = 42;`
(via `node` or `deno`) returns:
```
SyntaxError: Unexpected token (1:7)
    at Parser.pp$4.raise (file:///home/anonimito/work/open-source/Replete/node_modules/acorn/dist/acorn.mjs:3454:13)
    at Parser.pp$9.unexpected (file:///home/anonimito/work/open-source/Replete/node_modules/acorn/dist/acorn.mjs:750:8)
    at Parser.pp$8.parseVar (file:///home/anonimito/work/open-source/Replete/node_modules/acorn/dist/acorn.mjs:1295:12)
    at Parser.pp$8.parseVarStatement (file:///home/anonimito/work/open-source/Replete/node_modules/acorn/dist/acorn.mjs:1157:8)
    at Parser.pp$8.parseStatement (file:///home/anonimito/work/open-source/Replete/node_modules/acorn/dist/acorn.mjs:905:17)
    at Parser.pp$8.parseTopLevel (file:///home/anonimito/work/open-source/Replete/node_modules/acorn/dist/acorn.mjs:807:21)
    at Parser.parse (file:///home/anonimito/work/open-source/Replete/node_modules/acorn/dist/acorn.mjs:580:15)
    at Function.parse (file:///home/anonimito/work/open-source/Replete/node_modules/acorn/dist/acorn.mjs:630:35)
    at parse (file:///home/anonimito/work/open-source/Replete/node_modules/acorn/dist/acorn.mjs:5570:17)
    at scriptify_module (file:///home/anonimito/work/open-source/Replete/scriptify_module.js:96:16) {
  pos: 7,
  loc: Position { line: 1, column: 7 },
  raisedAt: 8
}
```

I had a quick look through Acorn's plugins https://github.com/orgs/acornjs/repositories?type=all and I don't see one specifically for Typescript. I also see https://github.com/g-plane/acorn-typescript but it's unmaintained.

So, possible plan-of-attack: Compile TS input into JS before passing it to the core of Replete?

**Comment by jamesdiacono** [comment]
That's the wun. You will need to modify your "source", "read" and "mime" capabilities. Here is a `compile_typescript` function that worked for me.

```
import typescript from "./typescript.js";
function compile_typescript(source) {
    return typescript.transpileModule(
        source,
        {
            compilerOptions: {
                module: typescript.ModuleKind.ES2015,
                newLine: "lf"
            }
        }
    ).outputText;
}
```

Even though JavaScript is a proper subset of TypeScript, you will need to prepend the transpiled files with `// @ts-nocheck` (in the "read" capability). Otherwise, Deno balks at the lack of type annotations.

**Comment by jamesdiacono** [comment]
Not that I condone the use of TypeScript! I just wanted to see if it was possible.

**Comment by anonimitoraf** [comment]
Sweet, thanks. I'll give it a try

**Comment by anonimitoraf** [comment]
I found this: https://github.com/Microsoft/TypeScript/issues/6387 with the added nicety of taking in your project's `tsconfig.json` if it eixsts
